### ISSUE TITLE
Assets / Fungus-Playmaker / FungusStateTransition.cs (3,7): Error CS0246: Could not find type or namespace name 'Fungus'. Are you missing a using directive or an assembly reference?

### ISSUE THREAD

**Issue by TrafficRider** [snozbot/fungus#1033]
I must warn you, I'm an absolute beginner :)
Stopped with such an error. How can I fix it?
Assets / Fungus-Playmaker / FungusStateTransition.cs (3,7): Error CS0246: Could not find type or namespace name 'Fungus'. Are
you missing a using directive or an assembly reference?
Unity version 5.3.0f4
![юнити ошибка](https://user-images.githubusercontent.com/73399534/137157434-0e93fea2-d2f6-4bec-893e-3ee4fee0fd20.PNG)

**Comment by Arylos07** [comment]
There are 2 potential issues here.

1) You are missing Fungus or it was not installed correctly. I don't know what Fungus-Playmaker is but it sounds like it's a collection of helper classes and does not include Fungus by default. If Fungus is installed, make sure it's not in any subfolders like Scripts/Fungus and all of its assets are in Assets/Fungus. The Unity Package in [Releases](https://github.com/snozbot/fungus/releases/tag/v3.13.7) should do this for you. 

2) I see you're using Unity 5. I know Unity 5 is in the minimum requirements but I don't think it's recommended with the curernt build. The oldest version I could get it working on was 2017. If everything else supports it and you're not in the middle of production, I would switch to a version like 2019-2020 since Fungus is stable on those versions. 

Let me know if nothing else is working; this doesn't seem to be a Fungus specific bug but more user-specific. I would also join the [Fungus Discord](https://discord.com/invite/99RqraQ) for one on one help.
