### ISSUE TITLE
Fungus is broken in 2018.2.0f2

### ISSUE THREAD

**Issue by fischp** [snozbot/fungus#696]
If you are getting an error from Rotorz.reorderablelistcontrol you need to get the source from here:
https://bitbucket.org/rotorz/reorderable-list-editor-field-for-unity/src

You need to replace the dll here: trunk\Assets\Fungus\Thirdparty\Reorderable List Field with the source code.

In the source code you need to comment out this line: 
_visibleRect = GUIHelper.VisibleRect();

located in ReorderableListControl.cs line 586.

This lets the flow chart work again.

**Comment by stevehalliwell** [comment]
Can you elaborate on the comment out line 586. I'd like to have an unaltered rotorz if we can.

**Comment by fischp** [comment]
I think commenting this out disables your ability to drag items to the point where dragging them should make the view scroll. Not a critical issue, but I guess it matters.

I didn't really do a deep dive here. I figured out the line causing the error and commented it out, and once that worked I didn't pursue the issue further.

I assume it relies on something that got deprecated from unity, but that is just a guess.

The underlying issue is probably with rotorz itself because this error comes from all reorderable lists in fungus, so I'm not sure you can keep using an unaltered rotorz.

I am using a pretty crazy version of fungus though because I have torn it all apart to have pretty extensive live2d support in order to make a game kind of like nekopara.

**Comment by penandlim** [comment]
Unity 2018.2.0f2.

Just deleting "\Assets\Fungus\Thirdparty\Reorderable List Field\Editor\Editor.ReorderableList.dll" and replacing the contents inside Reorderable List Field folder with [source code from here](https://bitbucket.org/rotorz/reorderable-list-editor-field-for-unity/get/master.zip) seems to fix the issue. 

@fischp I didn't have to comment out the source code at all, just had to replace dll. Scrolling the view while dragging an element still works. Might be because [Lea Hayes updated the code 3 days ago](https://bitbucket.org/rotorz/reorderable-list-editor-field-for-unity/commits/6b1c21e6a60ab5d4ce359ca16fa2bef1ed371050). You should try updating the source code again and see if it works without editing ReorderableListControl.cs.
