### ISSUE TITLE
[Solved] Flowchart UI is bugging out

### ISSUE THREAD

**Issue by CG-Tespy** [snozbot/fungus#780]
I updated my Fungus fork to the latest version a couple days ago, and am working on integrating a system I made for Fungus. While doing so, I noticed that the Flowchart UI (in both its window and the Block inspector) were... well, just look at the attached image. 

I'm using Unity 2019.2.9f1. 
![FungusUIBug](https://user-images.githubusercontent.com/22418199/69488079-cdac5b80-0e32-11ea-9313-a372c5347f28.png)

**Comment by stevehalliwell** [comment]
Latest master would have been at 2019.2.12 so the Unity downgrade process may have caused some things to become disconnected. This looks like what happens when the FungusEditorResources are not setup correctly. You can find them in the project or via the Project Settings->Fungus.

If that's not the issue, please paste any errors from the console or a screen cap of them.

**Comment by CG-Tespy** [comment]
Looking in ProjectSettings, I got a message about how FungusEditorResources needs to be regenerated. How do I do that? As for console errors (or warnings, to be precise), I got these:

1. 
null texture passed to GUI.DrawTexture
UnityEngine.GUI:DrawTexture(Rect, Texture, ScaleMode)
Fungus.EditorUtils.FlowchartWindow:DrawRectConnection(Rect, Rect, Boolean) (at Assets/Fungus/Scripts/Editor/FlowchartWindow.cs:1674)
Fungus.EditorUtils.FlowchartWindow:DrawConnections(Block) (at Assets/Fungus/Scripts/Editor/FlowchartWindow.cs:1582)
Fungus.EditorUtils.FlowchartWindow:DrawFlowchartView(Event) (at Assets/Fungus/Scripts/Editor/FlowchartWindow.cs:1334)
Fungus.EditorUtils.FlowchartWindow:OnGUI() (at Assets/Fungus/Scripts/Editor/FlowchartWindow.cs:731)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr) (at C:/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:179)

2.
null texture passed to GUI.DrawTexture
UnityEngine.GUI:DrawTexture(Rect, Texture, ScaleMode)
Fungus.EditorUtils.FlowchartWindow:DrawRectConnection(Rect, Rect, Boolean) (at Assets/Fungus/Scripts/Editor/FlowchartWindow.cs:1675)
Fungus.EditorUtils.FlowchartWindow:DrawConnections(Block) (at Assets/Fungus/Scripts/Editor/FlowchartWindow.cs:1582)
Fungus.EditorUtils.FlowchartWindow:DrawFlowchartView(Event) (at Assets/Fungus/Scripts/Editor/FlowchartWindow.cs:1334)
Fungus.EditorUtils.FlowchartWindow:OnGUI() (at Assets/Fungus/Scripts/Editor/FlowchartWindow.cs:731)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr) (at C:/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:179)

-

According to the console, both each happened 16 times.

**Comment by stevehalliwell** [comment]
Once you have the FungusEditorResources asset selected, in it's inspector there should be a button at the top "Sync with EditorResources folder". That'll locate and assign all the textures in there. Thanks for posting the errors those do look like what happens when all the required FungusEditorResource textures are null.

**Comment by CG-Tespy** [comment]
I did as you said, and the UI is now fixed. Thanks :)
